#! /bin/bash
# Setup for dotfiles

# Link the zprezto folder into home
ln -s $HOME/dotfiles/.zprezto $HOME/.zprezto

# Run the prezto setup script
source .zprezto/setup

# Link the .vim directory into home
ln -s $HOME/dotfiles/.vim $HOME/.vim

# Link all dotfiles in this directory into home directory
DOTFILES=`ls -p | egrep -v ".*[/]$|setup"`
for file in $DOTFILES
do
  echo $file
  ln -s $HOME/dotfiles/$file $HOME/.$file
done
