---
- name: install system deps
  sudo: yes
  apt: 
    pkg: "{{item}}"
    state: latest
    update_cache: yes
    cache_valid_time: 36000
  with_items:
    - git
    - python
    - python-virtualenv
    - ansible
    - scala
    - emacs
    - vim

- name: setup submodules
  shell: git submodule update --init --recursive chdir={{dotfiles_root}}
